"""changed uploadjobstatus to string

Revision ID: 2f1e59d630a2
Revises: bf3e83359345
Create Date: 2026-06-18 18:01:34.412402

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f1e59d630a2'
down_revision = 'bf3e83359345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploadjob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expected_image_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploadjob_job_id'), 'uploadjob', ['job_id'], unique=True)
    op.add_column('image', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('image', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('image', 'uploaded_at')
    op.drop_index(op.f('ix_uploadjob_job_id'), table_name='uploadjob')
    op.drop_table('uploadjob')
    # ### end Alembic commands ###
