"""add capture_time latitude longitude to image

Revision ID: 47f9c2007fbc
Revises: 3a1b2c4d5e6f
Create Date: 2026-07-29 14:54:18.428502

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '47f9c2007fbc'
down_revision = '3a1b2c4d5e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('capture_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('image', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('image', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'longitude')
    op.drop_column('image', 'latitude')
    op.drop_column('image', 'capture_time')
    # ### end Alembic commands ###
