"""alter capture_time to naive and add index

Revision ID: 9f77bd0d1e2c
Revises: 47f9c2007fbc
Create Date: 2026-09-01 15:37:29.352128

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f77bd0d1e2c'
down_revision = '47f9c2007fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'capture_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # B-tree index on capture_time for datetime filter query performance
    try:
        with op.get_context().autocommit_block():
            op.create_index(
                "ix_image_capture_time",
                "image",
                ["capture_time"],
                unique=False,
                postgresql_concurrently=True,
            )
    except Exception:
        op.create_index("ix_image_capture_time", "image", ["capture_time"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.get_context().autocommit_block():
            op.drop_index("ix_image_capture_time", table_name="image", postgresql_concurrently=True)
    except Exception:
        op.drop_index("ix_image_capture_time", table_name="image")
    op.alter_column('image', 'capture_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###
